source 'https://github.com/lyleLH/MTSpecs.git'
source 'https://github.com/CocoaPods/Specs.git'
#source 'https://cdn.cocoapods.org/'                  #官方仓库地址 cdn




use_frameworks!

platform :ios, '9.0'

target 'MTAppCenter_Example' do
  
  pod 'MTCategoryComponent'
  pod 'MTAppCenter', :path => '../'

  target 'MTAppCenter_Tests' do
    inherit! :search_paths

    
  end
end
